---

# SQL Server odbc and tools
# https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server
- name: Add homebrew taps
  homebrew_tap:
    name: "{{ item.tap }}"
    url: "{{ item.url }}"
    update_homebrew: no
    state: present
  loop: "{{ homebrew_taps }}"

- name: Add homebrew font taps
  homebrew_tap:
    name: "{{ item.tap }}"
    update_homebrew: no
    state: present
  loop: "{{ homebrew_font_taps }}"

- name: Update and upgrade homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install packages
  homebrew:
    name: homebrew_packages
    state: present

- name: Install cask packages
  homebrew_cask:
    name: homebrew_cask_packages
    state: present
