---

- name: Prepare pathogen directories
  file:
    path: "~/.vim/{{ item }}"
    state: directory
  loop:
    - autoload
    - bundle

- name: Get pathogen
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "~/.vim/autoload/pathogen.vim"

- name: Copy vimrc
  copy:
    src: "/tmp/dotfiles/vim/.vimrc"
    dest: "~/.vimrc"

- name: Get indentLine
  git:
    repo: "https://github.com/Yggdroot/indentLine.git"
    dest: "~/.vim/bundle/"
    clone: yes

- name: Get nerdtree
  git:
    repo: "https://github.com/preservim/nerdtree.git"
    dest: "~/.vim/bundle/"
    clone: yes
